# fly.toml app configuration file generated for fhirpath-lab-go on 2025-10-05T20:44:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fhirpath-lab-go'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
